blogit-main/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/<str:username>/', views.userBlog, name="user-blog"),
    path('myblog/', views.myBlog, name="my-blog"),
    path('friends/', views.friends, name="friends"),
    path('post/<slug:post_slug>/', views.post, name="post"),
    path('category/<slug:category_slug>/', views.posts_by_category, name="by_category"),
    path('tag/<slug:tag_slug>', views.posts_by_tag, name="by_tag"),
    path('create-post/', views.createPost, name="create-post"),
    path('update-post/<str:pk>', views.updatePost, name="update-post"),
    path('delete-post/<str:pk>', views.deletePost, name="delete-post"),
    path('like/<int:post_id>', views.like_post, name='like_post'),
    path('bookmark/<int:post_id>', views.bookmark_post, name='bookmark_post'),
    path('bookmarks/', views.user_bookmarks, name='user_bookmarks'),
]

blogit-main/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),    
    path('', include('users.urls')),
    path('', include('polls.urls')),
    path('', include('quizzes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogit-main/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('polls/', views.questions, name='questions'),
    path('question/<int:question_id>/', 
    	views.question, name='question'),
    path('question/<int:question_id>/results/', 
    	views.results, name='results'),
    path('question/<int:question_id>/vote/', 
    	views.vote, name='vote'),
]

blogit-main/quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
    path('quizzes/', views.quizzes, name='quizzes'),
    path('<int:quiz_id>/', views.display_quiz, 
    	name='display_quiz'),
    path('<int:quiz_id>/questions/<int:question_id>', 
    	views.display_question, name='display_question'),
    path('<int:quiz_id>/questions/<int:question_id>/grade/', 
    	views.grade_question, name='grade_question'),
    path('results/<int:quiz_id>/', views.quiz_results, 
    	name='quiz_results'),
    
]

blogit-main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Blog it! Платформа для увлеченных людей</title>
        <link rel="shortcut icon"
              type="image/x-icon"
              href="{% static 'favicon.ico' %}">
        <link rel="stylesheet"
              href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
        <meta name="theme-color" content="#ffffff">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300;400;500;600;700;800&amp;display=swap"
              rel="stylesheet">
        <link href="{% static 'assets/css/theme.css' %}" rel="stylesheet" />
        <link href="{% static 'assets/css/user.css' %}" rel="stylesheet" />
        <link href="{% static 'vendors/prism/prism.css' %}" rel="stylesheet">
    </head>
    <body>
        <main class="main" id="top">
            {% include 'navbar.html' %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {{ message.tags }} alert-dismissible col-5"
                         role="alert"
                         id="alert">
                        <strong>{{ message }}</strong>
                        <button type="button"
                                class="btn-close"
                                data-bs-dismiss="alert"
                                aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock content %}
        </main>
        <section class="py-0 bg-black">
            <div class="container">
                <div class="row justify-content-md-between justify-content-evenly py-4">

                </div>
            </div>
        </section>
        <script src="{% static 'vendors/popper/popper.min.js' %}"></script>
        <script src="{% static 'vendors/bootstrap/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendors/anchorjs/anchor.min.js' %}"></script>
        <script src="{% static 'vendors/is/is.min.js' %}"></script>
        <script src="{% static 'vendors/lodash/lodash.min.js' %}"></script>
        <script src="{% static 'vendors/fontawesome/all.min.js' %}"></script>
        <script src="https://polyfill.io/v3/polyfill.min.js?features=window.scroll"></script>
        <script src="{% static 'vendors/prism/prism.js' %}"></script>
        <script src="{% static 'assets/js/theme.js' %}"></script>
    </body>
</html>

blogit-main/templates/delete_template.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="mt-5 mb-5">
            <div class="vh-100 d-flex justify-content-center align-items-center">
                <div class="container">
                    <div class="row d-flex justify-content-center">
                        <div class="col-12 col-md-8 col-lg-6">
                            <div class="card card-bg">
                                <div class="card-body p-5">
                                    <form class="form" action="" method="POST">
                                        {% csrf_token %}
                                        <p class="text-200 fw-bold text-center">Вы действительно хотите удалить "{{ object }}"?</p>
                                        <div class="text-center">
                                            <a class="btn btn-success rounded-pill my-2 mr-btn"
                                               href="{% url 'account' %}">Отменить</a>
                                            <input class="btn btn-danger rounded-pill my-2"
                                                   type="submit"
                                                   value="Удалить"/>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

blogit-main/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3"
     data-navbar-on-scroll="data-navbar-on-scroll">
    <div class="container">
        <a class="navbar-brand" href="{% url 'profiles' %}"><span class="text-primary fs-3 ms-2 fw-bolder">Blog</span><span class="fw-bold text-300 fs-3">it!</span></a>
        <button class="navbar-toggler collapsed"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse pt-4 pt-lg-0"
             id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto border-bottom border-lg-bottom-0 pt-2 pt-lg-0">
                {% if not request.user.is_authenticated %}
                    <li class="nav-item px-2">
                        <a class="nav-link active"
                           aria-current="page"
                           href="{% url 'landing' %}">Главная</a>
                    </li>
                {% endif %}
                <li class="nav-item px-2">
                    <a class="nav-link" aria-current="page" href="{% url 'profiles' %}">Пользователи</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'blog:friends' %}">Друзья</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'blog:my-blog' %}">Блог</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'polls:questions' %}">Опросы</a>
                </li>
                <li class="nav-item px-2">
                    <a class="nav-link" href="{% url 'quizzes:quizzes' %}">Тесты</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{% url 'inbox' %}">Сообщения</a>
                    </li>
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{% url 'account' %}">Аккаунт</a>
                    </li>
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item px-2">
                        <a class="nav-link" href="{% url 'login' %}">Вход / Регистрация</a>
                    </li>
                {% endif %}
            </ul>
            <div class="d-flex mt-2 align-items-center mt-lg-0">
                <div class="dropdown"></div>
            </div>
        </div>
    </div>
</nav>

blogit-main/templates/pagination.html
{% if queryset.has_other_pages %}
    <div class="text-center">
        <ul class="list-unstyled list-inline my-2">
            {% if queryset.has_previous %}
                <li class="list-inline-item">
                    <a href="?page={{ queryset.previous_page_number }}"
                       class="btn page-link"
                       data-page="{{ queryset.previous_page_number }}">&#10094; Предыдущая</a>
                </li>
            {% endif %}
            {% for page in custom_range %}
                {% if page == queryset.number %}
                    <li class="list-inline-item">
                        <a href="?page={{ page }}" class="btn page-link" data-page="{{ page }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="list-inline-item">
                        <a href="?page={{ page }}" class="btn page-link" data-page="{{ page }}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            {% if queryset.has_next %}
                <li class="list-inline-item">
                    <a href="?page={{ queryset.next_page_number }}"
                       class="btn page-link"
                       data-page="{{ queryset.next_page_number }}">Следующая &#10095;</a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

blogit-main/templates/socials.html
<ul class="list-unstyled list-inline my-2">
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.github }}"><i class="fab fa-github-square fa-2x social-icons"></i></a>
    </li>
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.twitter }}"><i class="fab fa-twitter-square fa-2x social-icons"></i></a>
    </li>
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.linkedin }}"><i class="fab fa-linkedin fa-2x social-icons"> </i></a>
    </li>
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.youtube }}"><i class="fab fa-youtube-square fa-2x social-icons"></i></a>
    </li>
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.website }}"><i class="fa fa-globe fa-2x social-icons"></i></a>
    </li>
    <li class="list-inline-item">
        <a class="text-decoration-none" href="{{ profile.email }}"><i class="fa fa-envelope-square fa-2x social-icons"></i></a>
    </li>
</ul>

blogit-main/templates/tags_categories.html
<div class="text-start mt-3 px-3">
    <h5 class="text-500">Категории</h5>
    <ul class="list-unstyled">
        {% for category in categories %}
            <li>
                <a class="text-decoration-none fw-bold px-2"
                   href="{% url 'blog:by_category' category.slug %}"><i class="fas fa-chevron-circle-right mr-icon"></i>{{ category.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>
<div class="text-start mt-3 px-3">
    <h5 class="text-500">Теги</h5>
    <div class="col-12 container-fluid px-0">
        {% for tag in tags %}
            <a href="{% url 'blog:by_tag' tag.slug %}"><span class="badge rounded-pill text-400 pill-bg my-2">{{ tag.name }}</span></a>
        {% endfor %}
    </div>
</div>