blogit-main/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/<str:username>/', views.userBlog, name="user-blog"),
    path('myblog/', views.myBlog, name="my-blog"),
    path('friends/', views.friends, name="friends"),
    path('post/<slug:post_slug>/', views.post, name="post"),
    path('category/<slug:category_slug>/', views.posts_by_category, name="by_category"),
    path('tag/<slug:tag_slug>', views.posts_by_tag, name="by_tag"),
    path('create-post/', views.createPost, name="create-post"),
    path('update-post/<str:pk>', views.updatePost, name="update-post"),
    path('delete-post/<str:pk>', views.deletePost, name="delete-post"),
    path('like/<int:post_id>', views.like_post, name='like_post'),
    path('bookmark/<int:post_id>', views.bookmark_post, name='bookmark_post'),
    path('bookmarks/', views.user_bookmarks, name='user_bookmarks'),
]

blogit-main/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),    
    path('', include('users.urls')),
    path('', include('polls.urls')),
    path('', include('quizzes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogit-main/quizzes/urls.py
from django.urls import path

from . import views

app_name = 'quizzes'

urlpatterns = [
    path('quizzes/', views.quizzes, name='quizzes'),
    path('<int:quiz_id>/', views.display_quiz, 
    	name='display_quiz'),
    path('<int:quiz_id>/questions/<int:question_id>', 
    	views.display_question, name='display_question'),
    path('<int:quiz_id>/questions/<int:question_id>/grade/', 
    	views.grade_question, name='grade_question'),
    path('results/<int:quiz_id>/', views.quiz_results, 
    	name='quiz_results'),
    
]

blogit-main/quizzes/models.py
from django.db import models
from django.contrib.auth.models import User


class Quiz(models.Model):
    name = models.CharField(max_length=120)
    published = models.DateTimeField(auto_now_add=True)
     
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['published']
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

class Question(models.Model):
    class qtype(models.TextChoices):
        single = 'single'
        multiple = 'multiple'
   
    name = models.CharField(max_length=350)
    qtype = models.CharField(max_length=8, choices=qtype.choices, default=qtype.single)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    explanation = models.CharField(max_length=550)


    def get_answers(self):
        if self.qtype == 'single':
            return self.answer_set.filter(is_correct=True).first()
        else:
            qs = self.answer_set.filter(is_correct=True).values()
            return [i.get('name') for i in qs]


    def user_can_answer(self, user):
        user_choices = user.choice_set.all()
        done = user_choices.filter(question=self)
        print(done)
        if done.exists():
            return False
        return True

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

class Choice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
     
class Result(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)

blogit-main/quizzes/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from users.utils import paginateObjects
from django.contrib.auth.decorators import login_required
from django.db.models import F
from .models import Quiz, Question, Answer, Choice, Result

@login_required
def quizzes(request):
    profile = request.user.profile
    quizzes = Quiz.objects.all()
    custom_range, quizzes = paginateObjects(request, 
        quizzes, 3)
    context = {'quizzes': quizzes, 'profile': profile, 
               'custom_range': custom_range}
    return render(request, 
        'quizzes/quizzes.html', context)

@login_required
def display_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = quiz.question_set.first()
    return redirect(reverse('quizzes:display_question', 
        kwargs={'quiz_id': quiz_id, 
        'question_id': question.pk}))

@login_required
def display_question(request, quiz_id, question_id):
    profile = request.user.profile
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = quiz.question_set.all()
    current_question, next_question = None, None
    for ind, question in enumerate(questions):
        if question.pk == question_id:
            current_question = question
            if ind != len(questions) - 1:
                next_question = questions[ind + 1]
    context = {'quiz': quiz, 
    'question': current_question, 
    'next_question': next_question, 
    'profile': profile}
    return render(request,
        'quizzes/display.html',context)

@login_required
def grade_question(request, quiz_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    can_answer = question.user_can_answer(request.user)
    try:
        if not can_answer:
            return render(request, 
                'quizzes/partial.html',  
                {'question': question,
                'error_message': 'Вы уже отвечали на этот вопрос.'})

        if question.qtype == 'single':
            correct_answer = question.get_answers()
            user_answer = question.answer_set.get(pk=request.POST['answer'])
            choice = Choice(user=request.user, 
                question=question, answer=user_answer)
            choice.save()
            is_correct = correct_answer == user_answer
            result, created = Result.objects.get_or_create(user=request.user, 
                quiz=quiz)
            if is_correct is True:
                result.correct = F('correct') + 1
            else:
                result.wrong = F('wrong') + 1
            result.save()

        elif question.qtype == 'multiple':
            correct_answer = question.get_answers()
            answers_ids = request.POST.getlist('answer')
            user_answers = []
            if answers_ids:
                for answer_id in answers_ids:
                    user_answer = Answer.objects.get(pk=answer_id)
                    user_answers.append(user_answer.name)
                    choice = Choice(user=request.user, 
                        question=question, answer=user_answer)
                    choice.save()
                is_correct = correct_answer == user_answers 
                result, created = Result.objects.get_or_create(user=request.user, 
                    quiz=quiz)
                if is_correct is True:
                    result.correct = F('correct') + 1
                else:
                    result.wrong = F('wrong') + 1
                result.save()

    except:
        return render(request, 'quizzes/partial.html', 
            {'question': question})
    return render(
            request,'quizzes/partial.html',
            {'is_correct': is_correct, 
            'correct_answer': correct_answer, 
            'question': question})

@login_required
def quiz_results(request, quiz_id):
    profile = request.user.profile
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = quiz.question_set.all()
    results = Result.objects.filter(user=request.user, 
        quiz=quiz).values()
    correct = [i['correct'] for i in results][0]
    wrong = [i['wrong'] for i in results][0]
    context = {'quiz': quiz, 
    'profile': profile, 
    'correct': correct, 
    'wrong': wrong, 
    'number': len(questions), 
    'skipped': len(questions) - (correct + wrong)}
    return render(request, 
        'quizzes/results.html', context)

blogit-main/quizzes/templates/quizzes/display.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <a class="btn btn-danger rounded-pill btn-sm mb-3"
                                               href="{% url 'quizzes:quizzes' %}"><i class="fa fa-arrow-circle-left"></i> К тестам</a>
                                            <h6 class="fw-bold fs-1 text-200 my-3">{{ question.name }}</h6>
                                        </div>
                                    </div>
                                    <div>
                                        <form id="question-form"
                                              action="{% url 'quizzes:grade_question' quiz.id question.id %}"
                                              method="post">
                                            {% csrf_token %}
                                            {% if question.qtype == 'single' %}
                                                <div class="text-center">Только один ответ здесь - правильный.</div>
                                                {% for answer in question.answer_set.all %}
                                                    <div class="form-check">
                                                        <input type="radio"
                                                               name="answer"
                                                               class="form-check-input"
                                                               id="answer{{ forloop.counter }}"
                                                               value="{{ answer.id }}"/>
                                                        <label for="answer{{ forloop.counter }}" class="text-200">{{ answer.name }}</label>
                                                    </div>
                                                {% endfor %}
                                            {% else %}
                                                <div class="text-center">Здесь несколько правильных ответов.</div>
                                                {% for answer in question.answer_set.all %}
                                                    <div class="form-check">
                                                        <input type="checkbox"
                                                               name="answer"
                                                               class="form-check-input"
                                                               id="answer{{ forloop.counter }}"
                                                               value="{{ answer.id }}"/>
                                                        <label for="answer{{ forloop.counter }}" class="text-200">{{ answer.name }}</label>
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                            <div class="text-center">
                                                <input type="submit"
                                                       value="Ответить"
                                                       class="btn btn-warning rounded-pill mt-4"/>
                                            </div>
                                        </form>
                                        <div id="question-feedback" class="col-12 mt-3 text-200 text-center"></div>
                                    </div>
                                    <div class="my-4">
                                        {% if next_question %}
                                            <div class="mt-5">
                                                <a href="{% url 'quizzes:display_question' quiz.id next_question.id %}"
                                                   class="btn btn-primary btn-md rounded-pill"><i class="fa fa-arrow-circle-right"></i> Следующий вопрос</a>
                                            </div>
                                        {% else %}
                                            <div class="text-200">
                                                Это последний вопрос теста. После ответа нажмите кнопку
                                                <a href="{% url 'quizzes:quiz_results' quiz.id %}"
                                                   class="btn btn-primary rounded-pill btn-md">Посмотреть результаты</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
    <script>
     const form = document.getElementById("question-form");
    form.addEventListener("submit", (e) => {
        e.preventDefault();
        fetch(form.action, {method:'post', body: new FormData(form)})
            .then((response) => response.text())
            .then(text => {
                document.getElementById("question-feedback").innerHTML = text;
            });
    });

    


    </script>
{% endblock %}

blogit-main/quizzes/templates/quizzes/partial.html
{% if error_message %}
    <span class="message-card bg-danger px-4 py-4 fw-bold">{{ error_message }}</span>
{% elif is_correct %}
    <span class="message-card bg-success px-4 py-4 fw-bold mb-3">Правильно.</span>
    <span class="message-card bg-success px-4 py-4 fw-bold">{{ question.explanation }}</span>
{% elif is_correct == None %}
    <span class="message-card bg-warning px-4 py-4 fw-bold">Не выбран вариант ответа. Не забудьте ответить позже!</span>
{% else %}
    {% if correct_answer|length > 1 %}
        <div class="message-card bg-danger px-4 py-4 fw-bold mb-3">
            Неверно! Правильные ответы:
            <ul class="list-unstyled mt-2">
                {% for answer in correct_answer %}<li>{{ answer }}</li>{% endfor %}
            </ul>
        </div>
    {% else %}
        <span class="message-card bg-danger px-4 py-4 fw-bold  mb-3">Неверно! Правильный ответ: {{ correct_answer }}</span>
    {% endif %}
    <span class="message-card bg-success px-4 py-4 fw-bold">{{ question.explanation }}</span>
{% endif %}

blogit-main/quizzes/templates/quizzes/quizzes.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <h6 class="fw-bold fs-1 text-200 my-3">Тесты</h6>
                                        </div>
                                    </div>
                                    <div>
                                        {% for quiz in quizzes %}
                                            <div class="message-card card-soft-primary mt-4">
                                                <div class="card-body px-4">
                                                    <span class="text-end">{{ quiz.published }}</span>
                                                    <h6 class="fs--1 text-400 py-3">{{ quiz.name }}</h6>
                                                    <div class="text-center mb-3">
                                                        <a href="{% url 'quizzes:display_quiz' quiz.id %}"
                                                           class="btn btn-primary rounded-pill btn-sm">Пройти</a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="my-4">{% include 'pagination.html' with queryset=quizzes custom_range=custom_range %}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock %}

blogit-main/quizzes/templates/quizzes/results.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <a class="btn btn-danger rounded-pill btn-sm mb-3"
                                               href="{% url 'quizzes:quizzes' %}"><i class="fa fa-arrow-circle-left"></i> К тестам</a>
                                            <h6 class="fw-bold fs-1 text-200 my-3">{{ question.name }}</h6>
                                        </div>
                                    </div>
                                    <div>
                                        <h5 class="text-200 fs--1">Результаты пользователя {{ request.user.username }}</h5>
                                        <h5 class="text-400">{{ quiz }}</h5>
                                        <div class="table-responsive mt-5">
                                            <table class="table">
                                                <thead>
                                                    <tr>
                                                        <th scope="col" class="text-primary text-center">Показатели</th>
                                                        <th scope="col" class="text-primary text-center">Результаты</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td class="text-200 fw-bold text-center">Всего вопросов в тесте</td>
                                                        <td class="text-200 fw-bold text-center">{{ number }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-200 fw-bold text-center">Правильные ответы</td>
                                                        <td class="text-200 fw-bold text-center">{{ correct }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-200 fw-bold text-center">Неправильные ответы</td>
                                                        <td class="text-200 fw-bold text-center">{{ wrong }}</td>
                                                    </tr>
                                                    <tr>
                                                        <td class="text-200 fw-bold text-center">Пропущено вопросов</td>
                                                        <td class="text-200 fw-bold text-center">{{ skipped }}</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock %}