blogit-main/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/<str:username>/', views.userBlog, name="user-blog"),
    path('myblog/', views.myBlog, name="my-blog"),
    path('friends/', views.friends, name="friends"),
    path('post/<slug:post_slug>/', views.post, name="post"),
    path('category/<slug:category_slug>/', views.posts_by_category, name="by_category"),
    path('tag/<slug:tag_slug>', views.posts_by_tag, name="by_tag"),
    path('create-post/', views.createPost, name="create-post"),
    path('update-post/<str:pk>', views.updatePost, name="update-post"),
    path('delete-post/<str:pk>', views.deletePost, name="delete-post"),
    path('like/<int:post_id>', views.like_post, name='like_post'),
    path('bookmark/<int:post_id>', views.bookmark_post, name='bookmark_post'),
    path('bookmarks/', views.user_bookmarks, name='user_bookmarks'),
]

blogit-main/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),    
    path('', include('users.urls')),
    path('', include('polls.urls')),
    path('', include('quizzes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogit-main/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from pytils.translit import slugify


class Category(models.Model):
    name = models.CharField('category', max_length=20)
    slug = models.SlugField()

    class Meta:
        ordering = ['id']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField('tag', max_length=20)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['id']
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def __str__(self):
        return self.name


class Post(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    text = models.TextField(max_length=2000)
    category = models.ForeignKey(Category,
                                 on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, blank=True)
    published = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User,
                                   related_name='post_likes', blank=True)
    bookmarks = models.ManyToManyField(User,
                                       related_name='bookmarks', blank=True)

    def get_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1
        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}{num}"
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.get_unique_slug()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-published']
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return f'{self.owner} {self.title}'

    def number_of_likes(self):
        if self.likes.count() == 0:
            return ''
        else:
            return self.likes.count()

    def number_of_bookmarks(self):
        if self.bookmarks.count() == 0:
            return ''
        else:
            return self.bookmarks.count()

    def number_of_comments(self):
        if self.comments.count() == 0:
            return ''
        else:
            return self.comments.filter(approved=True).count()


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE, related_name='comments')
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    text = models.TextField()
    published = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-published']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

blogit-main/blog/forms.py
from django.forms import ModelForm
from django import forms
from .models import Post, Comment, Category

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'category', 
        'tags', 'text']
        labels = {
            'title': 'Название',
            'category':'Категория',
            'tags':'Теги', 
            'text':'Текст',
            }

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }
        category = forms.ModelChoiceField(queryset=Category.objects.none(), 
            empty_label="(Работа)")
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control input-box form-ensurance-header-control'})    
        self.fields['category'].empty_label = None
        

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

        labels = {
            'text': 'Ваш комментарий'
        }

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'form-control input-box form-ensurance-header-control'}) 

blogit-main/blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Tag, Category
from django.contrib import messages
from django.http import HttpResponseRedirect
from users.models import Profile
from .forms import PostForm, CommentForm
from .utils import searchPosts
from users.utils import paginateObjects


@login_required
def createPost(request):
    profile = request.user.profile
    form = PostForm()

    if request.method == 'POST':
        request.POST.getlist('tags')
        newtags = request.POST.get('newtags').replace(',', " ").split()
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save()
            post.owner = profile
            post.save()

            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                post.tags.add(tag)

            return redirect("blog:my-blog")

    context = {'form': form}
    return render(request, "blog/post_form.html", context)


@login_required
def userBlog(request, username):
    profile = Profile.objects.get(username=username)
    posts = profile.post_set.all()
    tags, categories = get_tags_categories(posts)
    custom_range, posts = paginateObjects(request, posts, 3)

    context = {'profile': profile, 'posts': posts,
               'tags': tags, 'categories': categories,
               'custom_range': custom_range}

    return render(request, "blog/user-blog.html", context)


@login_required
def post(request, post_slug):
    post = Post.objects.get(slug=post_slug)
    profile = request.user.profile
    comments = post.comments.filter(approved=True)
    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        comment = form.save(commit=False)
        comment.post = post
        comment.owner = request.user.profile
        comment.save()
        messages.success(request, 'Ваш комментарий появится после проверки модератором')
        return redirect('blog:post', post_slug=post.slug)
    return render(request, 'blog/single-post.html',
                  {'post': post, 'profile': profile,
                   'comments': comments, 'form': form})


def get_tags_categories(posts):
    categories = set()
    tags = set()
    for post in posts:
        categories.add(post.category)
        for tag in post.tags.all():
            tags.add(tag)
    return tags, categories


@login_required
def myBlog(request):
    profile = request.user.profile
    posts = profile.post_set.all()
    tags, categories = get_tags_categories(posts)

    custom_range, posts = paginateObjects(request, posts, 3)
    context = {'profile': profile, 'posts': posts,
               'custom_range': custom_range, 'tags': tags,
               'categories': categories}
    return render(request, 'blog/my-blog.html', context)


@login_required
def updatePost(request, pk):
    profile = request.user.profile
    post = profile.post_set.get(id=pk)
    form = PostForm(instance=post)

    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',', " ").split()

        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                post.tags.add(tag)

            return redirect('blog:my-blog')

    context = {'form': form, 'post': post}
    return render(request, "blog/post_form.html", context)


@login_required
def deletePost(request, pk):
    profile = request.user.profile
    post = profile.post_set.get(id=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:my-blog')
    context = {'object': post}
    return render(request, 'delete_template.html', context)


@login_required
def like_post(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        if not post.likes.filter(id=request.user.id).exists():
            post.likes.add(request.user)
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            post.likes.remove(request.user)
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def bookmark_post(request, post_id):
    if request.method == "POST":
        post = get_object_or_404(Post, pk=post_id)
        if not post.bookmarks.filter(id=request.user.id).exists():
            post.bookmarks.add(request.user)
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            post.bookmarks.remove(request.user)
            post.save()
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def friends(request):
    print("++++++++++")
    profile = request.user.profile
    print("!!!!!!!!!!!!!!", profile)
    posts = Post.objects.filter(
        owner__in=profile.follows.all()
    )

    tags, categories = get_tags_categories(posts)
    posts, search_query = searchPosts(request)
    custom_range, posts = paginateObjects(request, posts, 3)
    context = {'profile': profile, 'posts': posts,
               'search_query': search_query,
               'custom_range': custom_range,
               'tags': tags, 'categories': categories}
    return render(request, 'blog/post_list.html', context)


@login_required
def user_bookmarks(request):
    profile = request.user.profile
    user = request.user
    posts = Post.objects.filter(bookmarks__in=[user])
    tags, categories = get_tags_categories(posts)

    custom_range, posts = paginateObjects(request, posts, 3)
    context = {'profile': profile, "posts": posts,
               'custom_range': custom_range,
               'tags': tags, 'categories': categories}

    return render(request, "blog/post_list.html", context)


@login_required
def posts_by_category(request, category_slug):
    profile = request.user.profile
    category = get_object_or_404(Category, slug=category_slug)
    posts = Post.objects.filter(category__slug__contains=category_slug)
    tags, categories = get_tags_categories(posts)

    custom_range, posts = paginateObjects(request, posts, 3)
    context = {'profile': profile, 'posts': posts,
               'custom_range': custom_range, 'tags': tags,
               'category': category, 'categories': categories}
    return render(request, "blog/post_list.html", context)


@login_required
def posts_by_tag(request, tag_slug):
    profile = request.user.profile
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Post.objects.filter(tags__in=[tag])
    tags, categories = get_tags_categories(posts)

    custom_range, posts = paginateObjects(request, posts, 3)
    context = {'profile': profile, 'posts': posts,
               'custom_range': custom_range, 'tags': tags,
               'tag': tag, 'categories': categories}
    return render(request, "blog/post_list.html", context)

blogit-main/blog/templates/blog/my-blog.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary  ">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'blog:create-post' %}">Новая запись</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:friends' %}">Избранное</a>
                                                    </div>
                                                    {% include 'tags_categories.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <h6 class="fw-bold fs-1 text-200 my-3">Мои записи</h6>
                                        </div>
                                    </div>
                                    <div>
                                        {% for post in posts %}
                                            <div class="message-card mb-3">
                                                <div class="card-header fs--1 fw-bold">
                                                    <div class="d-flex justify-content-between">
                                                        <a class="text-decoration-none mt-2" href=""><span class="text-start">{{ post.category }}</span></a>
                                                        <span class="text-end icon-group"><a class="icon-item" href="{% url 'blog:update-post' post.id %}"><i class="uil uil-edit fs--1"></i></a><a class="icon-item" href="{% url 'blog:delete-post' post.id %}"><i class="uil uil-times-circle fs--1"></i></a></span>
                                                    </div>
                                                </div>
                                                <div class="card-body px-4 py-4">
                                                    <h5 class="card-title text-400">{{ post.title }}</h5>
                                                    <p class="card-text text-400">{{ post.text|safe|truncatewords:"50" }}</p>
                                                    <div class="text-end">
                                                        <a class="btn btn-primary rounded-pill btn-md my-2"
                                                           href="{% url 'blog:post' post.slug %}">Читать</a>
                                                    </div>
                                                </div>
                                                {% include 'blog/post_footer.html' %}
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="my-4">{% include 'pagination.html' with queryset=posts custom_range=custom_range %}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock content %}

blogit-main/blog/templates/blog/post_footer.html
<div class="card-footer text-muted d-flex justify-content-between">
    <div class="text-start">
        <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
                {% if user in post.likes.all %}
                    <form action="{% url 'blog:like_post' post.id  %}"
                          method="post"
                          name="dislike"
                          id="dislikeform">
                        {% csrf_token %}
                        <button type='submit'
                                name='dislike'
                                value="{{ post.id }}"
                                class="btn btn-link p-0 mt-0 text-decoration-none">
                            <i class="fa fa-heart mr-icon text-danger"></i>{{ post.number_of_likes }}
                        </button>
                    </form>
                {% else %}
                    <form action="{% url 'blog:like_post' post.id  %}"
                          method="post"
                          name="like"
                          id="likeform">
                        {% csrf_token %}
                        <button type='submit'
                                name='like'
                                value="{{ post.id }}"
                                class="btn btn-link p-0 mt-0">
                            <i class="fa fa-heart mr-icon text-muted"></i>{{ post.number_of_likes }}
                        </button>
                    </form>
                {% endif %}
            </li>
            <li class="list-inline-item">
                {% if user in post.bookmarks.all %}
                    <form action="{% url 'blog:bookmark_post' post.id  %}"
                          method="post"
                          name="remove"
                          id="remove">
                        {% csrf_token %}
                        <button type='submit'
                                name='remove'
                                value="{{ post.id }}"
                                class="btn btn-link p-0 mt-0">
                            <i class="fa fa-star mr-icon text-warning"></i>{{ post.number_of_bookmarks }}
                        </button>
                    </form>
                {% else %}
                    <form action="{% url 'blog:bookmark_post' post.id  %}"
                          method="post"
                          name="add"
                          id="add">
                        {% csrf_token %}
                        <button type='submit'
                                name='add'
                                value="{{ post.id }}"
                                class="btn btn-link p-0 mt-0">
                            <i class="fa fa-star mr-icon text-muted"></i>{{ post.number_of_bookmarks }}
                        </button>
                    </form>
                {% endif %}
            </li>
        </ul>
    </div>
    <div class="text-center">
        {% for tag in post.tags.all %}
            <a href="{% url 'blog:by_tag' tag.slug %}"><span class="badge rounded-pill text-400 pill-bg">{{ tag.name }}</span></a>
        {% endfor %}
    </div>
    {% if post.number_of_comments %}
        <div class="text-end">
            <a class="text-decoration-none mt-2"
               href="{% url 'blog:post' post.slug %}#comments">Комментарии: {{ post.number_of_comments }}</a>
        </div>
    {% else %}
        <div class="text-end">
            <a class="text-decoration-none mt-2"
               href="{% url 'blog:post' post.slug %}">Комментировать</a>
        </div>
    {% endif %}
</div>

blogit-main/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'blog:friends' %}">Друзья</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:user_bookmarks' %}">Избранное</a>
                                                    </div>
                                                    {% include 'tags_categories.html' %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            {% if 'friends' in request.path %}
                                                <h6 class="fw-bold fs-1 text-200 my-3">Записи друзей</h6>
                                                <div class="row">
                                                    <div class="mx-auto col-10 col-md-12 col-lg-12 mb-3">
                                                        <form class="text-light" action="{% url 'blog:friends' %}" method="get">
                                                            <div class="input-group-icon">
                                                                <input class="form-control form-ensurance-control"
                                                                       type="text"
                                                                       name="search_query"
                                                                       value="{{ search_query }}"
                                                                       id="formInput#search"
                                                                       placeholder="Поиск по записям друзей"
                                                                       aria-label="search"/>
                                                                <button class="btn btn-primary btn-subscribe" type="submit">Найти</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                {% elif 'bookmarks' in request.path %}
                                                    <h6 class="fw-bold fs-1 text-200 my-3">Избранное</h6>
                                                {% elif 'category' in request.path %}
                                                    <h6 class="fw-bold fs-1 text-200 my-3">
                                                        Все записи в категории <span class="fw-bolder text-400">{{ category.name }}</span>
                                                    </h6>
                                                {% elif 'tag' in request.path %}
                                                    <h6 class="fw-bold fs-1 text-200 my-3">
                                                        Все записи, отмеченные тегом <span class="fw-bolder text-400">{{ tag.name }}</span>
                                                    </h6>
                                                {% endif %}
                                            </div>
                                        </div>
                                        <div>
                                            {% for post in posts %}
                                                <div class="message-card mb-3">
                                                    <div class="card-header fs--1 fw-bold">
                                                        <div class="d-flex justify-content-between">
                                                            <a class="text-decoration-none mt-2" href=""><span class="text-start">{{ post.category }}</span></a>
                                                            {% if request.user.profile.id == post.owner.id %}
                                                                <span class="text-end icon-group"><a class="icon-item" href="{% url 'blog:update-post' post.id %}"><i class="uil uil-edit fs--1"></i></a><a class="icon-item" href="{% url 'blog:delete-post' post.id %}"><i class="uil uil-times-circle fs--1"></i></a></span>
                                                            {% else %}
                                                                <span class="text-end mt-2">{{ post.published }}</span>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                    <div class="card-body px-4">
                                                        <h5 class="card-title text-400 p-2">{{ post.title }}</h5>
                                                        <div class="row g-0">
                                                            <div class="col-md-3 caption center-block">
                                                                <div class="blog-image-wrapper mt-2">
                                                                    <div class="blog-image">
                                                                        <img src="{{ post.owner.image.url }}" alt="profile" />
                                                                    </div>
                                                                </div>
                                                                <p class="text-200 fw-bold mt-3">
                                                                    <a class="text-decoration-none"
                                                                       href="{% url 'user-profile' post.owner.username %}">{{ post.owner.name }}</a>
                                                                </p>
                                                            </div>
                                                            <div class="col-md-9">
                                                                <p class="card-text text-400 p-2">{{ post.text|safe|truncatewords:"50" }}</p>
                                                            </div>
                                                        </div>
                                                        <div class="text-end">
                                                            <a class="btn btn-primary rounded-pill btn-md my-2"
                                                               href="{% url 'blog:post' post.slug %}">Читать</a>
                                                        </div>
                                                    </div>
                                                    {% include 'blog/post_footer.html' %}
                                                </div>
                                            {% endfor %}
                                        </div>
                                        <div class="my-4">{% include 'pagination.html' with queryset=posts custom_range=custom_range %}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </section>
    {% endblock content %}