blogit-main/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('blog/<str:username>/', views.userBlog, name="user-blog"),
    path('myblog/', views.myBlog, name="my-blog"),
    path('friends/', views.friends, name="friends"),
    path('post/<slug:post_slug>/', views.post, name="post"),
    path('category/<slug:category_slug>/', views.posts_by_category, name="by_category"),
    path('tag/<slug:tag_slug>', views.posts_by_tag, name="by_tag"),
    path('create-post/', views.createPost, name="create-post"),
    path('update-post/<str:pk>', views.updatePost, name="update-post"),
    path('delete-post/<str:pk>', views.deletePost, name="delete-post"),
    path('like/<int:post_id>', views.like_post, name='like_post'),
    path('bookmark/<int:post_id>', views.bookmark_post, name='bookmark_post'),
    path('bookmarks/', views.user_bookmarks, name='user_bookmarks'),
]

blogit-main/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),    
    path('', include('users.urls')),
    path('', include('polls.urls')),
    path('', include('quizzes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blogit-main/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('polls/', views.questions, name='questions'),
    path('question/<int:question_id>/', 
    	views.question, name='question'),
    path('question/<int:question_id>/results/', 
    	views.results, name='results'),
    path('question/<int:question_id>/vote/', 
    	views.vote, name='vote'),
]

blogit-main/polls/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    name = models.CharField(max_length=300)
    published = models.DateTimeField(auto_now_add=True)

    def user_voted(self, user):
        user_votes = user.vote_set.all()
        done = user_votes.filter(question=self)
        if done.exists():
            return False
        return True
    
    class Meta:
        ordering = ['published']
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.name


class Choice(models.Model):
    question = models.ForeignKey(Question, 
        on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    class Meta:
        verbose_name = 'Варианты'
        verbose_name_plural = 'Варианты'

    def __str__(self):
        return self.name

class Vote(models.Model):
    user = models.ForeignKey(User, 
        on_delete=models.CASCADE)
    question = models.ForeignKey(Question, 
        on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, 
        on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Голосование'
        verbose_name_plural = 'Голосования'

    def __str__(self):
        return f'{self.question.name[:15]} - {self.choice.name[:15]} - {self.user.username}'

blogit-main/polls/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Question, Vote
from django.contrib import messages
from users.utils import paginateObjects

@login_required()
def questions(request):
    profile = request.user.profile
    questions = Question.objects.all()
    custom_range, questions = paginateObjects(request, questions, 3)
    context = {'questions': questions, 'custom_range': custom_range, 'profile': profile}
    return render(request, 'polls/questions.html', context)

@login_required()
def question(request, question_id):
    profile = request.user.profile
    question = Question.objects.get(pk=question_id)
    context = {'question': question, 
    'profile': profile}
    return render(request, 
        'polls/question.html', context)

@login_required()
def results(request, question_id):
    profile = request.user.profile
    question = get_object_or_404(Question, pk=question_id)
    labels = []
    data = []
    votes = question.choice_set.select_related('question').all() 
    for item in votes:
        labels.append(item.name)
        data.append(item.votes)
    context = {'question': question, 
    'profile': profile, 
    'labels': labels, 
    'data': data}    
    return render(request, 
        'polls/results.html', context)

@login_required()
def vote(request, question_id):
    profile = request.user.profile
    question = get_object_or_404(Question, pk=question_id)
    try:
        user_choice = question.choice_set.get(pk=request.POST['choice'])
        if not question.user_voted(request.user):
            messages.error(request, 
                'Вы уже голосовали в этом опросе.')
            return render(request, 
                'polls/question.html',  
                {'question': question,'profile': profile})
        if user_choice:
            user_choice.votes += 1
            user_choice.save()
            vote = Vote(user=request.user, question=question, choice=user_choice)
            vote.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
    except (KeyError, UnboundLocalError):
        messages.error(request, 'Вы не выбрали вариант ответа!')
        return render(request, 'polls/question.html', {'question': question})
    return render(request, 
        'polls/results.html', 
        {'question': question, 'profile': profile})

blogit-main/polls/templates/polls/question.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <a class="btn btn-danger rounded-pill btn-sm mb-3"
                                               href="{% url 'polls:questions' %}"><i class="fa fa-arrow-circle-left"></i> К опросам</a>
                                            <h6 class="fw-bold fs-1 text-200 my-3">{{ question.name }}</h6>
                                        </div>
                                    </div>
                                    <div class="container col-8 mb-3 mt-4">
                                        <form action="{% url 'polls:vote' question.id %}" method="post">
                                            {% csrf_token %}
                                            {% for choice in question.choice_set.all %}
                                                <div class="form-check">
                                                    <input type="radio"
                                                           name="choice"
                                                           class="form-check-input"
                                                           id="choice{{ forloop.counter }}"
                                                           value="{{ choice.id }}"/>
                                                    <label for="choice{{ forloop.counter }}" class="text-200">{{ choice.name }}</label>
                                                </div>
                                            {% endfor %}
                                            <div class="text-center">
                                                <input type="submit"
                                                       value="Голосовать"
                                                       class="btn btn-warning rounded-pill mt-4"/>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="my-4"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock %}

blogit-main/polls/templates/polls/questions.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <h6 class="fw-bold fs-1 text-200 my-3">Опросы и голосования</h6>
                                        </div>
                                    </div>
                                    <div>
                                        {% for question in questions %}
                                            <div class="message-card card-soft-primary mt-4">
                                                <div class="card-body px-4">
                                                    <span class="text-end">{{ question.published }}</span>
                                                    <h6 class="fs--1 text-400 py-3">{{ question.name }}</h6>
                                                    <div class="text-center mb-3">
                                                        <a href="{% url 'polls:question' question.id %}"
                                                           class="btn btn-primary rounded-pill btn-sm">Голосовать</a>
                                                        <a href="{% url 'polls:results' question.id %}"
                                                           class="btn btn-warning rounded-pill btn-sm">Результаты</a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <div class="my-4">{% include 'pagination.html' with queryset=questions custom_range=custom_range %}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock %}

blogit-main/polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <main class="mt-5 mb-5">
            <div class="container">
                <div class="main-body">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="card p-3 card-soft-primary">
                                <div class="card-body">
                                    <div class="d-flex flex-column align-items-center text-center">
                                        <div class="profile-image-wrapper mt-5">
                                            <div class="profile-image">
                                                <img src="{{ profile.image.url }}" alt="profile" />
                                            </div>
                                        </div>
                                        <div class="mt-1">
                                            <h5 class="fw-bold fs-2 text-200 mb-5 text-center">{{ profile.name }}</h5>
                                            <div class="text-center">
                                                <div class="col-12 d-grid">
                                                    <div class="text-center">
                                                        <a class="btn btn-primary rounded-pill my-2 col-9"
                                                           href="{% url 'account' %}">Мой профиль</a>
                                                        <a class="btn btn-warning rounded-pill my-2 col-9"
                                                           href="{% url 'blog:my-blog' %}">Мой блог</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <hr class="my-4">
                                    <div class="text-center">{% include 'socials.html' %}</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-8">
                            <div class="card p-3 h-100 card-soft-primary">
                                <div class="profile-card-body">
                                    <div class="row mb-3">
                                        <div class="col-12">
                                            <a class="btn btn-danger rounded-pill btn-sm mb-3"
                                               href="{% url 'polls:questions' %}"><i class="fa fa-arrow-circle-left"></i> К опросам</a>
                                            <h6 class="fw-bold fs-1 text-200 my-3">{{ question.name }}</h6>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th scope="col" class="text-primary text-center">Вариант ответа</th>
                                                    <th scope="col" class="text-primary text-center">Количество голосов</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for choice in question.choice_set.all %}
                                                    <tr>
                                                        <td class="text-400 fw-bold text-center">{{ choice.name }}</td>
                                                        <td class="text-400 fw-bold text-center">{{ choice.votes }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <div class="row justify-content-center">
                                        <div class="col-8 container-fluid my-5">
                                            <canvas id="myChart"></canvas>
                                        </div>
                                    </div>
                                    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                                    <script>
  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'doughnut',
    data: {
      labels: {{ labels|safe }},
      datasets: [{
        label: 'Количество голосов',
        data: {{ data|safe }},
        borderWidth: 1
      }]
    },

  });
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </section>
{% endblock %}